### ISSUE TITLE
Could you provide a license 

### ISSUE THREAD

**Issue by fabianbormann** [MartifyLabs/mesh#10]
Hi there,

your project is still very cool! It would be great if you could provide a LICENSE file to root of the project and also add that license to the license field the package.json (and maybe - if you want - remove the "private: true").

Thanks,
Fabian

**Comment by jinglescode** [comment]
Hi Fabian (@fabianbormann), thanks for checking out Mesh. Yes, we have added a license in a development branch (so much has been added and tested), it will be merged to the main as soon as are we ready to do so (in less than 10 days).

**Comment by jinglescode** [comment]
Excited to update that we have merged it with the `main` branch. We have also deployed a new [Playground](https://mesh.martify.io/). Happy exploring.
