### ISSUE TITLE
Add sample to lock the policy when minting assets

### ISSUE THREAD

**Issue by ggcaponetto** [MartifyLabs/mesh#13]
The current [samples](https://mesh.martify.io/apis/transaction) shows the minting of assets with no policy locking.

How would one achieve policy locking?

Digging deeper, I discovered that I can add the expiry to the ``forgeScript`` . In order to do this, the csl library should be exposed by the module, but it is not, I guess.

Any advice is appreciated!

**Comment by abdelkrimdev** [comment]
`ForgeScript` provide a factory method called `fromNativeScript` you can use it to pass a `JSON` NativeScript object in case the already provided factories aren't enough to fulfill your requirements. we also export a type called `NativeScript` you can import it using `import type { NativeScript } from '@martifylabs/mesh'` you can use it to make sure the script you are passing is valid

**Comment by jinglescode** [comment]
> 

Hi @ggcaponetto, 
you can include NativeScript to define the forging script (for example if you want to have a policy locking script), you can do this:

```
import type { NativeScript } from '@martifylabs/mesh';

const nativeScript: NativeScript = {
  type: 'all',
  scripts:
  [
    {
      type: 'before',
      slot: '<insert slot here>'
    },
    {
      type: 'sig',
      keyHash: '<insert keyHash here>'
    }
  ]
};

const forgingScript = ForgeScript.fromNativeScript(nativeScript);
```

Hope this helps.

**Comment by ggcaponetto** [comment]
Thanks a lot!
