### ISSUE TITLE
Sending exact lovelace values with assets

### ISSUE THREAD

**Issue by eschudt** [MartifyLabs/mesh#50]
Could there be an option to include any minimum ADA required as part of the transaction amount to send?

For instance, in the example below, the final lovelace value that will be built is around 4.3 ADA due to the minimum amount required to send assets. 

There should be an option to take out the minimum required ADA from the lovelace amount specified so the amount to send after building the transaction will still be the specified ADA - 3ADA in this case.

```
    const tx = new Transaction({ initiator: wallet })
        .sendLovelace(
          'someAddress',
          '3000000'
        )
        .sendAssets(
          'someAddress',
          [
            {
              unit: 'someAsset',
              quantity: '1',
            },
          ]
        );
```

**Comment by abdelkrimdev** [comment]
Hey @eschudt you can use `sendValue` method to do that 😄

**Comment by eschudt** [comment]
@abdelkrimdev I'm not sure how I missed that 😄
Thanks for your help! I'll close this issue.
